# Generated by Django 5.2.5 on 2025-09-05 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='categoria',
            field=models.CharField(choices=[('doces', 'Doces'), ('salgadas', 'Salgadas'), ('bebidas', 'Bebidas')], default='doces', max_length=20),
        ),
    ]
